import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/common/Header";
import Footer from "@/common/Footer";
import ChatButton from "@/components/chatbot/ChatButton";
import WowInitializer from "@/components/common/WowInitializer"
import { getAllMenus } from "@/actionCreator/home.actionCreator";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menus = await getAllMenus();
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo.png" />

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} ${dmSans.variable} antialiased`}
      >
        <WowInitializer />
        <Header data={menus?.data} />
        {children}
        <Footer />
        <ChatButton />
        {/* <ScrollToTopButton /> */}
        <Toaster position="top-right" richColors closeButton />
      </body>
    </html>
  );
}
